name: Deploy Prod
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy prod to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            cd ..
            cd /home/rootProject/InvoiceAppProd/InvoiceApp
            git pull
            npm install
            pm2 stop staging
            pm2 restart prod
            echo 'Deployment to prod successfully'
